spring:
  application:
    name: turbine
server:
  port: 7070
turbine:
  app-config: FeignDemo,HelloService
  clusterNameExpression: new String("default")
  aggregator:
    clusterConfig: default

eureka:
  client:
    service-url:
      defaultZone: http://node01:8081/eureka/,http://node02:8082/eureka/